vpc_name           = "prod-vpc"
cidr_block         = "10.2.0.0/16"
public_subnet_cidrs = ["10.2.1.0/24", "10.2.2.0/24"]
private_subnet_cidrs = ["10.2.3.0/24", "10.2.4.0/24"]
azs                = ["us-east-1a", "us-east-1b"]
cluster_name       = "prod-cluster"
desired_capacity   = 5
max_capacity       = 10
min_capacity       = 3
instance_type      = "m5.large"
key_name           = "my-key-pair-prod"
aws_region         = "us-east-1"
s3_bucket          = "my-terraform-state-prod"
dynamodb_table     = "terraform-lock-table-prod"
